// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna informações do usuário autenticado que está chamando o MCP (ID, e-mail, client ID).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Não autenticado." }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-connections.ts
import { createClient } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx: any) {
  return createClient(
    Deno.env.get("SELFHOSTED_SUPABASE_URL") ?? Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SELFHOSTED_SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY")!,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false },
      db: { schema: "zapp" }
    }
  );
}
var list_connections_default = defineTool2({
  name: "list_whatsapp_connections",
  title: "Listar conexões WhatsApp",
  description: "Lista as conexões WhatsApp (instâncias) visíveis para o usuário autenticado, respeitando RLS.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Máximo de conexões a retornar (padrão 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Não autenticado." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("whatsapp_connections").select("id, name, instance_id, phone_number, status, is_default, created_at").limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { connections: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.49.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx: any) {
  return createClient2(
    Deno.env.get("SELFHOSTED_SUPABASE_URL") ?? Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SELFHOSTED_SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY") ?? Deno.env.get("SUPABASE_ANON_KEY")!,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false },
      db: { schema: "zapp" }
    }
  );
}
var list_contacts_default = defineTool3({
  name: "search_contacts",
  title: "Buscar contatos",
  description: "Busca contatos por nome ou telefone (LIKE case-insensitive). Respeita RLS do usuário.",
  inputSchema: {
    query: z2.string().trim().min(1).max(120).describe("Termo de busca (nome ou telefone)."),
    limit: z2.number().int().min(1).max(50).optional().describe("Máximo de resultados (padrão 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Não autenticado." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("contacts").select("id, name, phone_number, email, assigned_to, created_at").or(`name.ilike.%${encodeURIComponent(query)}%,phone_number.ilike.%${encodeURIComponent(query)}%`).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var _supabaseUrlRaw = Deno.env.get("SELFHOSTED_SUPABASE_URL") ?? Deno.env.get("SUPABASE_URL");
if (!_supabaseUrlRaw) throw new Error("[mcp] SELFHOSTED_SUPABASE_URL or SUPABASE_URL env var is required");
var supabaseUrl = _supabaseUrlRaw;
var mcp_default = defineMcp({
  name: "zapp-web-mcp",
  title: "ZAPP Web MCP",
  version: "0.1.0",
  instructions: "Ferramentas para o ZAPP Web: identificação do usuário autenticado, listagem de conexões WhatsApp e busca de contatos. Todas as chamadas respeitam RLS do usuário.",
  auth: auth.oauth.issuer({
    issuer: `${supabaseUrl}/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_connections_default, list_contacts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
import { parseOrReject } from "../_shared/contract-kit.ts";
import { readJsonBodyOrEmpty } from "../_shared/validation.ts";
import { CONTRACT_SCHEMAS } from "../_shared/contract-schemas.ts";
import { getCorsHeaders } from "../_shared/cors.ts";

const _mcpHandler = createSupabaseHandler(mcp_default, { functionName: "mcp" });
Deno.serve(async (req: Request) => {
  // Contrato mcp@v1 (G4): gate apenas para chamadas sem body (GET/health check).
  // POSTs JSON-RPC do protocolo MCP (com body) são roteados intactos para o handler.
  if (req.body === null) {
    const parsed = parseOrReject('mcp', CONTRACT_SCHEMAS['mcp'], req, await readJsonBodyOrEmpty(req), {
      extraHeaders: getCorsHeaders(req),
    });
    if (parsed.ok === false) return parsed.response;
  }
  return _mcpHandler(req);
});
