-- ============================================================
-- 20260925160000_reconcile_drift_e025_e039_e28_e36_e12_rabbitmq_ownership_prospeccao.sql
-- Reconciliacao repo x DB: 14 migrations aplicadas diretamente no banco entre
-- 17/08 e 23/09/2026, nunca versionadas no repo (drift identificado via MCP
-- supabase_db_query em supabase_migrations.schema_migrations, 25/09/2026).
-- Regra README supabase/migrations: corpo = o que JA roda no DB (nunca
-- reintroduzir bug); idempotente (CREATE OR REPLACE / IF NOT EXISTS); registrada
-- como backfill/no-op no DB vivo. Nenhum DDL novo roda ao aplicar este arquivo.
-- Gerado por Hermes em 25/09/2026 via introspecao real (supabase-mcp.atomicabr.com.br).
--
-- ESCOPO: apenas registro/estrutura de objetos ja existentes. NAO altera GRANTs
-- nem RLS de nenhuma tabela (ver CARD 8 em _arquivo_zapp/CARDS_PENDENTES_20260925.md
-- para o achado de seguranca do schema prospeccao, tratado como card separado por
-- decisao explicita do Joaquim).
--
-- Migrations reconciliadas nesta fase (objetos com estrutura introspectavel):
--   20260830000001 plano100_e028_storage_buckets_privados
--   20260906001500 rabbitmq_orphan_queue_dumps
--   20260906120000 harden_ownership_crm_rpcs (GRANT/REVOKE, sem DDL de objeto)
--   20260915135302 create_prospeccao_schema
--   20260915135355 seed_empresas_radar_brindes (dados, ver nota)
--   20260923122452 add_sobrenome_column_prospeccao_contatos
--   20260923122851 fix_particulas_nome_sobrenome_prospeccao (UPDATE pontual)
--
-- Migrations SEM objeto persistente introspectavel (operacionais/pontuais,
-- registradas como no-op textual; nao ha CREATE/ALTER a repetir com seguranca):
--   20260817193000 e25_message_hourly_fdw_reconcile_delta1h
--   20260817200001 e39a_extra_webhook_v2_evo_reconciler_grants
--   20260820210000 p100_lane2_vacuum_full_e36_38 (VACUUM FULL, operacional)
--   20260820213000 p100_recon_v2_backfill_lid_e5_e19 (backfill de dados)
--   20260820215500 p100_kpi_v3_rollup_backlog_real_e49_e57_e59 (kpi_rollup_24h
--                  ja existe em evo.kpi_rollup_24h — tabela documentada abaixo)
--   20260830000002 plano100_e036_pii_access_logs (tabela zapp.pii_access_log ja
--                  existe — documentada abaixo)
--   20260830000003 plano100_e012_secdef_permissions_helpers (GRANT/REVOKE)
-- ============================================================

-- --------------------------------------------------------------
-- 20260830000001 plano100_e028_storage_buckets_privados
-- Buckets privados ja existentes no storage (confirmado via storage.buckets).
-- INSERT idempotente — nao sobrescreve buckets existentes.
-- --------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES
  ('zapp-reports', 'zapp-reports', false),
  ('zapp-exports', 'zapp-exports', false)
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------------
-- 20260906001500 rabbitmq_orphan_queue_dumps
-- Dump pontual (nao-destrutivo) das filas orfas messages.set/chats.set antes da
-- purga de 2026-09-06 (PLANO-100 etapa 11). Ver docs/PLANO_100_AUDITORIA_SCHEMA_EVO_2026-09-05.md.
-- --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS evo.rabbitmq_orphan_queue_dumps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_name text NOT NULL,
    dumped_at timestamp with time zone NOT NULL DEFAULT now(),
    message_count integer NOT NULL,
    payload jsonb NOT NULL,
    note text
);

COMMENT ON TABLE evo.rabbitmq_orphan_queue_dumps IS
  'Dump pontual (nao-destrutivo, ack_requeue_true) das filas orfas messages.set/chats.set antes da purga em 2026-09-06 (PLANO-100 etapa 11). Ver docs/PLANO_100_AUDITORIA_SCHEMA_EVO_2026-09-05.md.';

ALTER TABLE evo.rabbitmq_orphan_queue_dumps ENABLE ROW LEVEL SECURITY;

-- --------------------------------------------------------------
-- 20260820215500 p100_kpi_v3_rollup_backlog_real_e49_e57_e59 (parcial)
-- Materializacao 5-min dos agregados pesados do v_kpi_overview. Escrita por
-- fn_kpi_rollup_refresh (cron evo-kpi-rollup-5m); retencao 48h.
-- --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS evo.kpi_rollup_24h (
    snapshot_at timestamp with time zone NOT NULL DEFAULT now() PRIMARY KEY,
    msgs_1h bigint,
    msgs_24h bigint,
    last_ingest_at timestamp with time zone,
    dedup_failures_24h bigint,
    dedup_tracked_rows bigint,
    webhook_latency_avg_ms_24h numeric,
    webhook_latency_p95_ms_24h numeric,
    webhook_events_24h bigint,
    consumer_drop_total bigint,
    pct_401_24h numeric,
    ipwatch_hits_24h bigint
);

COMMENT ON TABLE evo.kpi_rollup_24h IS
  'Materializacao 5-min dos agregados pesados do v_kpi_overview (P100 e49/e59, 20/08). Escrita por fn_kpi_rollup_refresh (cron evo-kpi-rollup-5m); leitura pela view. Retencao 48h.';

ALTER TABLE evo.kpi_rollup_24h ENABLE ROW LEVEL SECURITY;

-- Backlog RabbitMQ historico (coletor via mgmt API, watchdog w9-consumer-stats).
CREATE TABLE IF NOT EXISTS evo.rabbitmq_backlog_history (
    captured_at timestamp with time zone NOT NULL DEFAULT now(),
    queue_name text NOT NULL,
    messages bigint,
    consumers integer,
    ready bigint,
    unacked bigint,
    source text DEFAULT 'rabbitmq-mgmt-api',
    PRIMARY KEY (captured_at, queue_name)
);

COMMENT ON TABLE evo.rabbitmq_backlog_history IS
  'Backlog RabbitMQ via mgmt API 15672 — PLANO-100 etapa 57. Coletor a estender no watchdog w9-consumer-stats (stack ag6-watchdogs): curl :15672/api/queues a cada 60s + INSERT. Alimenta v_kpi_overview.rabbitmq_backlog_messages (hoje NULL).';

ALTER TABLE evo.rabbitmq_backlog_history ENABLE ROW LEVEL SECURITY;

-- --------------------------------------------------------------
-- 20260830000002 plano100_e036_pii_access_logs
-- Modulo inativo/vazio ate 2026-08 (sprawl F-009); ver DICIONARIO. Estrutura ja
-- existe no DB com RLS habilitado (rls_enabled=true); esta migration so registra
-- a estrutura — RLS/policies NAO sao tocadas aqui (nao encontradas policies
-- explicitas; fora do escopo desta reconciliacao de registro).
-- --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS zapp.pii_access_log (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    accessed_by uuid REFERENCES auth.users(id),
    contact_id uuid,
    field text NOT NULL,
    accessed_at timestamp with time zone NOT NULL DEFAULT now(),
    source text
);

CREATE INDEX IF NOT EXISTS idx_pii_access_log_user
  ON zapp.pii_access_log USING btree (accessed_by, accessed_at DESC);

ALTER TABLE zapp.pii_access_log ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE zapp.pii_access_log IS
  'Modulo inativo/vazio ate 2026-08 (sprawl F-009); ver DICIONARIO.';

-- --------------------------------------------------------------
-- 20260915135302 create_prospeccao_schema
-- Schema de prospeccao B2B (empresas-alvo, contatos via Lusha/LeadContact,
-- execucoes de fluxo n8n, config de cookies de sessao). Confirmado via
-- introspecao: RLS DESABILITADO e GRANT a anon nas 4 tabelas — ver CARD 8,
-- tratado como achado de seguranca separado, NAO corrigido nesta migration.
-- --------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS prospeccao;

CREATE TABLE IF NOT EXISTS prospeccao.empresas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    nome_lusha text,
    setor text,
    cidade text,
    estado character(2),
    prioridade character(1) CHECK (prioridade = ANY (ARRAY['A'::bpchar, 'B'::bpchar, 'C'::bpchar])),
    departamentos text DEFAULT 'COMPRAS,MARKETING,RECURSOS HUMANOS'::text,
    status text NOT NULL DEFAULT 'pendente'::text
        CHECK (status = ANY (ARRAY['pendente'::text, 'em_andamento'::text, 'concluido'::text, 'erro'::text, 'pausado'::text])),
    cod_empresa_bitrix text,
    observacoes text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);
COMMENT ON TABLE prospeccao.empresas IS 'Empresas-alvo para prospecção de brindes corporativos';

CREATE INDEX IF NOT EXISTS idx_empresas_prioridade ON prospeccao.empresas USING btree (prioridade);

CREATE TABLE IF NOT EXISTS prospeccao.contatos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id integer NOT NULL REFERENCES prospeccao.empresas(id) ON DELETE CASCADE,
    nome text,
    cargo text,
    departamento text,
    telefone text,
    linkedin_url text,
    fonte_telefone text CHECK (fonte_telefone = ANY (ARRAY['leadcontact'::text, 'payload_phones'::text, 'manual'::text])),
    status text NOT NULL DEFAULT 'novo'::text
        CHECK (status = ANY (ARRAY['novo'::text, 'contatado'::text, 'aguardando'::text, 'interessado'::text, 'nao_interessado'::text, 'convertido'::text])),
    cod_contato_bitrix text,
    duplicata boolean NOT NULL DEFAULT false,
    notas text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    resumo text,
    localizacao text,
    setor text,
    foto_url text,
    experiencias jsonb DEFAULT '[]'::jsonb,
    competencias text[] DEFAULT '{}'::text[],
    idiomas text[] DEFAULT '{}'::text[],
    interesses text[] DEFAULT '{}'::text[],
    fonte_perfil text,
    telefones_todos jsonb,
    email text[],
    fonte_email text[],
    sobrenome text
);
COMMENT ON TABLE prospeccao.contatos IS 'Contatos encontrados via Lusha/LeadContact para cada empresa';

CREATE INDEX IF NOT EXISTS idx_contatos_email ON prospeccao.contatos USING gin (email);
CREATE INDEX IF NOT EXISTS idx_contatos_empresa ON prospeccao.contatos USING btree (empresa_id);
CREATE INDEX IF NOT EXISTS idx_contatos_linkedin ON prospeccao.contatos USING btree (linkedin_url);
CREATE INDEX IF NOT EXISTS idx_contatos_localizacao ON prospeccao.contatos USING btree (localizacao);

CREATE TABLE IF NOT EXISTS prospeccao.execucoes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id integer NOT NULL REFERENCES prospeccao.empresas(id) ON DELETE CASCADE,
    departamento text,
    total_encontrados integer DEFAULT 0,
    total_inseridos integer DEFAULT 0,
    total_duplicatas integer DEFAULT 0,
    status text NOT NULL DEFAULT 'iniciado'::text
        CHECK (status = ANY (ARRAY['iniciado'::text, 'concluido'::text, 'erro'::text, 'sem_resultado'::text])),
    erro_msg text,
    executado_por text,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);
COMMENT ON TABLE prospeccao.execucoes IS 'Histórico de cada execução do fluxo n8n por empresa/departamento';

CREATE INDEX IF NOT EXISTS idx_execucoes_empresa ON prospeccao.execucoes USING btree (empresa_id);

-- cookies_config: guarda credenciais de sessao (Lusha/LinkedIn). Estrutura
-- registrada aqui SEM os dados (dados nunca entram em migration/git). Ver CARD 8.
CREATE TABLE IF NOT EXISTS prospeccao.cookies_config (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico text NOT NULL,
    cookie text,
    token text,
    cnpj text,
    csrf_token text,
    atualizado_em timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone,
    is_healthy boolean,
    health_status text,
    health_error text,
    alerta_dias_antes integer DEFAULT 14,
    nota text,
    linkedin_cookie text,
    CONSTRAINT cookies_config_servico_key UNIQUE (servico)
);

CREATE OR REPLACE FUNCTION prospeccao.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_contatos_updated_at ON prospeccao.contatos;
CREATE TRIGGER trg_contatos_updated_at BEFORE UPDATE ON prospeccao.contatos
  FOR EACH ROW EXECUTE FUNCTION prospeccao.set_updated_at();

DROP TRIGGER IF EXISTS trg_empresas_updated_at ON prospeccao.empresas;
CREATE TRIGGER trg_empresas_updated_at BEFORE UPDATE ON prospeccao.empresas
  FOR EACH ROW EXECUTE FUNCTION prospeccao.set_updated_at();

-- --------------------------------------------------------------
-- 20260915135355 seed_empresas_radar_brindes
-- NO-OP DE REGISTRO: seed de dados de empresas-alvo, ja aplicado diretamente no
-- banco em 2026-09-15. Dados de negocio nao sao versionados em migration por
-- convencao deste repo (evitar PII/dado comercial em git). Registro apenas
-- textual — nenhum INSERT roda aqui.
--
-- 20260923122851 fix_particulas_nome_sobrenome_prospeccao
-- NO-OP DE REGISTRO: correcao pontual de dados (normalizacao de particulas em
-- nome/sobrenome, ex.: "de", "da", "dos") em prospeccao.contatos, ja aplicada em
-- 2026-09-23. Sem funcao/trigger persistente para reconstruir (era UPDATE unico).
-- --------------------------------------------------------------

-- --------------------------------------------------------------
-- 20260923122452 add_sobrenome_column_prospeccao_contatos
-- Coluna 'sobrenome' ja incluida na definicao de prospeccao.contatos acima
-- (CREATE TABLE IF NOT EXISTS nao adiciona coluna em tabela existente).
-- Guarda idempotente para o caso da tabela existir sem a coluna:
-- --------------------------------------------------------------
ALTER TABLE prospeccao.contatos ADD COLUMN IF NOT EXISTS sobrenome text;

-- --------------------------------------------------------------
-- Migrations operacionais sem DDL a repetir (registro textual apenas):
--   20260817193000 e25_message_hourly_fdw_reconcile_delta1h — reconciliacao FDW
--     pontual de delta horario; sem objeto persistente encontrado (proname
--     ILIKE '%hourly%recon%' e '%fdw_reconcile%' retornaram vazio).
--   20260817200001 e39a_extra_webhook_v2_evo_reconciler_grants — GRANT/REVOKE
--     pontual em funcoes do webhook v2 evo; sem funcao com nome correspondente
--     encontrada na introspecao atual (pode ter sido renomeada/removida em
--     evolucao posterior do schema evo).
--   20260820210000 p100_lane2_vacuum_full_e36_38 — VACUUM FULL operacional (8
--     tabelas, cron 553 removido + fn dropada). Operacao unica, nao repetivel
--     por DDL.
--   20260820213000 p100_recon_v2_backfill_lid_e5_e19 — backfill de dados (65
--     registros @lid via FDW) + ajuste de fn_recon v2. Sem escopo de dado a
--     repetir em migration.
--   20260830000003 plano100_e012_secdef_permissions_helpers — GRANT/REVOKE de
--     helpers SECURITY DEFINER; sem DDL de objeto novo.
--   20260906120000 harden_ownership_crm_rpcs — ALTER FUNCTION ... OWNER TO
--     (hardening de ownership de RPCs do CRM); sem novo objeto a criar.
-- ============================================================
